# Generated by Django 4.1 on 2022-12-23 21:33

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='envs',
            field=picklefield.fields.PickledObjectField(default={}, editable=False),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Dicty',
        ),
    ]
