# Generated by Django 4.1 on 2022-12-23 21:37

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_apps_envs_delete_dicty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='envs',
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
    ]
