# Generated by Django 4.1 on 2022-12-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_remove_apps_envs_dicty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicty',
            name='key',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='dicty',
            name='value',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
