# Generated by Django 4.1 on 2022-12-24 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_dicty_key_alter_dicty_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicty',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envs', to='apps.apps'),
        ),
    ]
