# Generated by Django 4.1 on 2022-12-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_dicty_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
